---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}
    username: ${database.username}
    password: ${database.password}

database:
  name: hello_world
  host: localhost
  port: 5432
  username: benchmarkdbuser
  password: benchmarkdbpass

---
spring:
  profiles: jdbc

---
spring:
  profiles: pgclient

---
spring:
  profiles: rxjdbc

---
spring:
  profiles: r2dbc

---
spring:
  profiles: mongo

database:
  url: mongodb://localhost:27017/?waitQueueMultiple=200
  name: hello_world

---
spring:
  profiles:
    active: pgclient,postgres
